### ISSUE TITLE
Anonymity set greater than all DBCs ever issued?

### ISSUE THREAD

**Issue by cryptozeb** [scritcash/scrit-whitepaper#3]
It's mentioned twice that one could achieve a bigger anonymity set than all DBCs ever issued but no rational is given for that claim:

https://github.com/scritcash/scrit-whitepaper/blob/9d6812c82d7856acdc06198e691edf051387536e/scrit-whitepaper.md#L8

https://github.com/scritcash/scrit-whitepaper/blob/9d6812c82d7856acdc06198e691edf051387536e/scrit-whitepaper.md#L403-L405

It appears that "all DBCs issued" is the expected anonymity set during normal operation but that may be degraded by offline mints. Instead of a lower bound "all DBCs" should be an upper bound.

**Comment by JonathanLogan** [comment]
For the reduction on anonymity set by offline mints see my answer on #5. One might even want to introduce random recovery transactions to make that more resilient.

On size of anonymity set: You're completely right. It's a hold-over from a previous design phase and is wrong in this context.
