### ISSUE TITLE
Why include mint ID in signature part?

### ISSUE THREAD

**Issue by cryptozeb** [scritcash/scrit-whitepaper#5]
https://github.com/scritcash/scrit-whitepaper/blob/9d6812c82d7856acdc06198e691edf051387536e/scrit-whitepaper.md#L125-L127

Under normal operation conditions all mints should be online regularly, so there shouldn't be partially signed DBCs. That makes the inclusion of the ID redundant since the signatures could be included in a predefined order (e.g. ordered by mint ID). In the case one is missing that field could be filled with zeros. 

Furthermore timing dependent signature orders could potentially reduce the anonymity set.

It might not be a problem if it's never transmitted like that (it's mentioned that normally each mint only sees its own signatures), but why specify a purely local format at all then? I might have misunderstood the protocol here (see #4).

**Comment by JonathanLogan** [comment]
Inclusion of the MintID is purely for making implementation easier. The MintID-Currency-Amount-Epoch tuple can be used for direct lookup for the signature public key. During normal transactions with a mint the MintID isn't required and could be dropped.
For recovery transactions your proposal of predefined order might be more compact than including MintIDs, depending on the details of the serialization format which we haven't defined yet. Depending on that format the MintID would be either encoded directly or follow from the context.

Concerning anonymity set: For recovery transactions it makes sense to not include ALL collected signatures but only m signatures. Only m signatures are required by the protocol to work, and dropping any extra signatures makes communication more compact. These m signatures should be randomly sampled from all signatures already collected which helps to conceal leaking information about which mints have been offline during the transaction.
